### ISSUE TITLE
cannot load such file -- faraday (LoadError)

### ISSUE THREAD

**Issue by BHydden** [RubyMineshaft/ogs_katacheck#1]
Installation of Ruby went smoothly, as did the installation of ogs_katacheck
When I try to run ogs-katacheck OR katacheck I get the below error

```
Traceback (most recent call last):
        7: from C:/Ruby27-x64/bin/katacheck:23:in `<main>'
        6: from C:/Ruby27-x64/bin/katacheck:23:in `load'
        5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ogs_katacheck-0.1.4/bin/katacheck:3:in `<top (required)>'
        4: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ogs_katacheck-0.1.4/lib/ogs_katacheck.rb:1:in `<top (required)>'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- faraday (LoadError)
```

System:
Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Core i5 750 @ 2.67GHz	40 °C
	Lynnfield 45nm Technology
RAM
	12.0GB Dual-Channel DDR3 @ 532MHz (7-7-7-20)
Motherboard
	Gigabyte Technology Co. Ltd. P55M-UD2 (Socket 1156)	37 °C
Graphics
	SyncMaster (1920x1080@60Hz)
	P221W (1680x1050@59Hz)
	2047MB NVIDIA GeForce GTX 760 (Gigabyte)

**Comment by mattetress** [comment]
Looks like it didn't automatically install the dependencies. Try running `gem install faraday` and then try running it again.

**Comment by mattetress** [comment]
I fixed the dependency issue. Running `gem update ogs_katacheck` should fix it :)

**Comment by BHydden** [comment]
I accidentally implemented the first fix before reading the second 🤣 I did the second anyway and it worked both times, thanks
