### ISSUE TITLE
percentages seem low?

### ISSUE THREAD

**Issue by BHydden** [RubyMineshaft/ogs_katacheck#2]
Could you double-check how the percentages are counted?

I just analysed a game* that has 79 moves total... so 40 for black and 39 for white

As you can see in the below images, the percentages look like they're based on both players each making 158 moves

![image](https://user-images.githubusercontent.com/28991649/97056356-226ccf00-15cc-11eb-99d3-fb223b7af021.png)

*game link obscured for privacy; can be provided through PM on request

**Comment by mattetress** [comment]
Wow, that was a big oops! 

`gem update ogs_katacheck` and they should be good now.

**Comment by BHydden** [comment]
looks good, thanks
